sudo: false
language: ruby
rvm:
  - 2.3.7
before_install: 
- gem uninstall bundler
- gem install bundler
- bundle install

jobs:
  include:
    - stage: test
      script: 
        - bundle exec rspec
        - gem build xsort.gemspec