sudo: false
language: ruby
rvm:
  - 2.3.7
before_install: 
- gem install bundler -v 1.17.2
- bundle install

jobs:
  include:
    - stage: test
      script: 
        - bundle exec rspec
        - gem build xsort.gemspec